version: "3"
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=secret
  server:
    build: ..
    volumes:
      - ..:/usr/src/app
    environment:
      - PACT=1
    depends_on:
      - migrate
  migrate:
    build: ..
    command: ["python", "manage.py", "migrate"]
    volumes:
      - ..:/usr/src/app
    depends_on:
      - db
  http-verifier:
    image: dius/pact-provider-verifier-docker
    volumes:
      - ./http:/tmp/pacts
    environment:
      - pact_urls=/tmp/pacts/serlo.org-commenting_system.json
      - provider_base_url=http://server:8000
      - provider_states_url=http://server:8000/pact/
      - provider_states_active_url=http://server:8000/pact/
    depends_on:
      - server
  message-verifier:
    image: dius/pact-provider-verifier-docker
    volumes:
      - ./message:/tmp/pacts
    environment:
      - pact_urls=/tmp/pacts/serlo.org-commenting_system.json
      - provider_base_url=http://server:8000
      - provider_states_url=http://server:8000/pact/
      - provider_states_active_url=http://server:8000/pact/
    depends_on:
      - server